### ISSUE TITLE
[✨FEATURE ] MVC 패턴 적용 및 DB 연동

### ISSUE THREAD

**Issue by SHKim55** [Soft-Gallery/issue-management-backEnd#1]
## 구현해야하는 기능
- MVC 패턴 기반 스프링 부트 API 기본 서버 구축

## 작업 내용
- MVC 패턴 적용을 위한 Domain Model 적용
- JPA를 통한 Domain Model의 Entity화
- 설계된 Entity를 바탕으로 DB 스키마 설계

## 참고사항
- 1번 이슈는 내꺼얌.
- @dmstjdhdh 님 이슈 작성법 리뷰 부탁드립니다.

## 예상 작업 시간 및 마감일
- 금일(5/14) 작업 완성 목표

**Comment by RaccHoon** [comment]
폴더 구조, DB 연동, 클래스 명세 완료해서 dev branch에 합쳐주면, dev에서 branch 파서 feat2 시작하겠습니다

**Comment by SHKim55** [comment]
dev로 PR 올렸습니다. 리뷰 승인되면 머지할게요
