### ISSUE TITLE
[✨FEATURE ]Auth 개발

### ISSUE THREAD

**Issue by RaccHoon** [Soft-Gallery/issue-management-backEnd#2]
## 구현해야하는 기능
- JWT 토큰 발행 및 검증 로직 구현
- 회원가입 api 구현
- 로그인 api 구현

## 작업 내용
- JWT 사용을 위한 의존성 추가
- Security config 구현
- 회원가입 로직 구현
- 로그인 필터 구현
- JWT 발급 및 검증 기능 구현
- CORS 설정

## 참고사항
- 완료하면 unit test code 작성 작업을 하고, 문제가 없으면 프론트엔드와 통합 작업 진행하겠음.
- 프론트엔드에서 api를 요청할 때 CORS 설정을 안하면 403에러가 나기 때문에 프론트엔드의 URL을 등록을 해줘야 하는데, 아직 프론트엔드 배포가 안되서 URL이 없음. LocalHost만 등록해두고, 나중에 프론트엔드 배포되면 프론트엔드 URL도 등록해줘야 함.

## 예상 작업 시간 및 마감일
- 3시간
- 오늘 퇴근을 일찍 하면 오늘 안에 개발하고, 늦게 하면 내일까지 개발하겠음.

**Comment by SHKim55** [comment]
Front 배포도 미리 그냥 해버릴까? 용우랑 같이 조지면 얼마 안 걸릴거같은데

**Comment by SHKim55** [comment]
오키요 안 그래도 월요일에 하기로 함

**Comment by RaccHoon** [comment]
should make test code and connect front end
