### ISSUE TITLE
[✨FEATURE ] Swagger 어노테이션 부여

### ISSUE THREAD

**Issue by 1Kirl** [Soft-Gallery/issue-management-backEnd#44]
## 개선할 기능
Swagger API 문서 가독성 향상

## 작업 내용
Swagger를 이용해서 테스트를 진행하면서, 동시에
Swagger API 문서의 가독성을 높이기 위한 어노테이션을 붙이겠습니다.
(어짜피 스웨거로 테스트를 하기 때문에 어노테이션 붙이는 데에 시간이 그리 많이 소요되지 않는다고 판단했습니다.)

## 예상 작업 시간 및 마감일
1~2h

**Comment by SHKim55** [comment]
이슈 진행 중단
